// ============================================
// DoneFast - Mock Data for Development
// ============================================
import { Service, Order, JokiMember, DashboardStats, ChatMessage, Notification, Voucher } from '@/types';

export const SERVICES: Service[] = [
  {
    id: '1',
    name: 'Pembuatan Makalah & Essay',
    description: 'Penulisan makalah akademik, essay, dan paper dengan kualitas tinggi. Lengkap dengan referensi dan format sesuai standar.',
    category: 'akademik',
    base_price: 50000,
    rating: 4.9,
    total_orders: 1247,
    estimated_days: 3,
    features: ['Referensi lengkap', 'Anti plagiarisme', 'Format APA/MLA', 'Revisi 2x gratis'],
    is_popular: true,
    is_active: true,
  },
  {
    id: '2',
    name: 'Skripsi & Thesis',
    description: 'Bantuan penulisan skripsi, thesis, dan disertasi dari bab 1 sampai selesai. Bimbingan hingga ACC.',
    category: 'akademik',
    base_price: 500000,
    rating: 4.8,
    total_orders: 856,
    estimated_days: 14,
    features: ['Bab 1-5', 'Konsultasi dosen', 'Revisi unlimited', 'Turnitin check'],
    is_popular: true,
    is_active: true,
  },
  {
    id: '3',
    name: 'Presentasi PowerPoint',
    description: 'Desain presentasi profesional dengan animasi dan layout premium untuk seminar dan sidang.',
    category: 'akademik',
    base_price: 35000,
    rating: 4.9,
    total_orders: 2341,
    estimated_days: 2,
    features: ['Design premium', 'Animasi smooth', 'Custom template', 'Infografis'],
    is_popular: true,
    is_active: true,
  },
  {
    id: '4',
    name: 'Desain Arsitektur 3D',
    description: 'Pembuatan desain arsitektur 3D render, denah, dan gambar kerja lengkap menggunakan AutoCAD & SketchUp.',
    category: 'arsitektur',
    base_price: 200000,
    rating: 4.7,
    total_orders: 423,
    estimated_days: 7,
    features: ['Render 3D HD', 'Denah lengkap', 'AutoCAD files', 'Revisi 3x'],
    is_popular: false,
    is_active: true,
  },
  {
    id: '5',
    name: 'Desain Interior',
    description: 'Konsep desain interior modern minimalis dengan 3D visualization dan mood board.',
    category: 'arsitektur',
    base_price: 300000,
    rating: 4.8,
    total_orders: 312,
    estimated_days: 10,
    features: ['3D Visualization', 'Mood board', 'Material list', 'Layout plan'],
    is_popular: false,
    is_active: true,
  },
  {
    id: '6',
    name: 'Website Full Stack',
    description: 'Pembuatan website full stack dengan Next.js, React, atau framework modern lainnya. Responsive & SEO ready.',
    category: 'coding',
    base_price: 500000,
    rating: 4.9,
    total_orders: 678,
    estimated_days: 7,
    features: ['Full responsive', 'SEO optimized', 'Dashboard admin', 'Source code'],
    is_popular: true,
    is_active: true,
  },
  {
    id: '7',
    name: 'Mobile App Development',
    description: 'Pembuatan aplikasi mobile Android/iOS menggunakan React Native atau Flutter.',
    category: 'coding',
    base_price: 800000,
    rating: 4.7,
    total_orders: 234,
    estimated_days: 14,
    features: ['Cross-platform', 'UI/UX modern', 'API integration', 'Play Store ready'],
    is_popular: false,
    is_active: true,
  },
  {
    id: '8',
    name: 'Tugas Pemrograman',
    description: 'Pengerjaan tugas pemrograman dalam berbagai bahasa: Python, Java, C++, JavaScript, dll.',
    category: 'coding',
    base_price: 75000,
    rating: 4.8,
    total_orders: 1567,
    estimated_days: 2,
    features: ['Semua bahasa', 'Clean code', 'Dokumentasi', 'Penjelasan kode'],
    is_popular: true,
    is_active: true,
  },
  {
    id: '9',
    name: 'Konsultasi Akademik',
    description: 'Konsultasi 1-on-1 untuk tugas, skripsi, atau masalah akademik lainnya via chat atau video call.',
    category: 'konsultasi',
    base_price: 50000,
    rating: 4.9,
    total_orders: 890,
    estimated_days: 1,
    features: ['1-on-1 session', 'Video call', 'Chat 24/7', 'Follow up gratis'],
    is_popular: true,
    is_active: true,
  },
  {
    id: '10',
    name: 'Konsultasi Bisnis & Startup',
    description: 'Mentoring bisnis digital, startup, dan e-commerce dari praktisi berpengalaman.',
    category: 'konsultasi',
    base_price: 150000,
    rating: 4.6,
    total_orders: 156,
    estimated_days: 1,
    features: ['Business plan', 'Market analysis', 'Strategy session', 'Networking'],
    is_popular: false,
    is_active: true,
  },
  {
    id: '11',
    name: 'AI & Machine Learning',
    description: 'Implementasi solusi AI/ML: model training, NLP, computer vision, dan data science project.',
    category: 'ai_teknologi',
    base_price: 400000,
    rating: 4.8,
    total_orders: 189,
    estimated_days: 10,
    features: ['Custom model', 'Data preprocessing', 'Training & testing', 'Documentation'],
    is_popular: false,
    is_active: true,
  },
  {
    id: '12',
    name: 'Automation & Bot',
    description: 'Pembuatan bot otomasi: chatbot, trading bot, scraping bot, dan workflow automation.',
    category: 'ai_teknologi',
    base_price: 300000,
    rating: 4.7,
    total_orders: 267,
    estimated_days: 5,
    features: ['Custom bot', '24/7 running', 'API integration', 'Dashboard monitoring'],
    is_popular: false,
    is_active: true,
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'DF-ABC123',
    user_id: '1',
    service_id: '1',
    joki_id: '1',
    title: 'Makalah Ekonomi Makro',
    description: 'Makalah tentang dampak inflasi terhadap perekonomian Indonesia',
    requirements: 'Format APA, 15 halaman, referensi jurnal minimal 10',
    files: ['brief.pdf'],
    deadline: '2026-02-25',
    price: 150000,
    status: 'in_progress',
    difficulty: 'medium',
    pages: 15,
    revisions_left: 2,
    result_files: [],
    created_at: '2026-02-18T10:00:00Z',
    updated_at: '2026-02-18T12:00:00Z',
  },
  {
    id: 'DF-DEF456',
    user_id: '2',
    service_id: '6',
    joki_id: '2',
    title: 'Website E-Commerce',
    description: 'Website toko online dengan pembayaran dan dashboard admin',
    requirements: 'Next.js, Tailwind, integrasi Midtrans',
    files: ['wireframe.fig'],
    deadline: '2026-03-01',
    price: 1500000,
    status: 'in_progress',
    difficulty: 'hard',
    revisions_left: 3,
    result_files: [],
    created_at: '2026-02-15T08:00:00Z',
    updated_at: '2026-02-18T14:00:00Z',
  },
  {
    id: 'DF-GHI789',
    user_id: '3',
    service_id: '3',
    title: 'Presentasi Seminar',
    description: 'PPT untuk seminar proposal skripsi',
    requirements: 'Dark theme, modern, 25 slide',
    files: ['outline.docx'],
    deadline: '2026-02-20',
    price: 85000,
    status: 'pending_payment',
    difficulty: 'easy',
    pages: 25,
    revisions_left: 2,
    result_files: [],
    created_at: '2026-02-18T15:00:00Z',
    updated_at: '2026-02-18T15:00:00Z',
  },
];

export const MOCK_JOKI: JokiMember[] = [
  {
    id: '1',
    user_id: 'j1',
    name: 'Ahmad Rizky',
    skills: ['Makalah', 'Essay', 'Skripsi', 'Jurnal'],
    rating: 4.9,
    total_completed: 342,
    commission_rate: 60,
    is_available: true,
    avatar: undefined,
  },
  {
    id: '2',
    user_id: 'j2',
    name: 'Dina Pratiwi',
    skills: ['Web Development', 'React', 'Next.js', 'Node.js'],
    rating: 4.8,
    total_completed: 189,
    commission_rate: 55,
    is_available: true,
    avatar: undefined,
  },
  {
    id: '3',
    user_id: 'j3',
    name: 'Budi Santoso',
    skills: ['AutoCAD', 'SketchUp', '3D Render', 'ArchiCAD'],
    rating: 4.7,
    total_completed: 156,
    commission_rate: 50,
    is_available: false,
    avatar: undefined,
  },
  {
    id: '4',
    user_id: 'j4',
    name: 'Sarah Amelia',
    skills: ['Python', 'Machine Learning', 'Data Science', 'AI'],
    rating: 4.9,
    total_completed: 98,
    commission_rate: 65,
    is_available: true,
    avatar: undefined,
  },
];

export const MOCK_STATS: DashboardStats = {
  total_orders_today: 47,
  total_income_today: 12500000,
  active_users: 234,
  pending_orders: 12,
  in_progress_orders: 28,
  completed_orders: 1847,
  total_income_month: 187500000,
  total_profit_month: 75000000,
};

export const MOCK_CHAT: ChatMessage[] = [
  {
    id: '1',
    order_id: 'DF-ABC123',
    sender_id: '1',
    sender_role: 'customer',
    message: 'Halo, saya mau tanya progress makalah saya sudah sampai mana?',
    is_read: true,
    created_at: '2026-02-18T10:30:00Z',
  },
  {
    id: '2',
    order_id: 'DF-ABC123',
    sender_id: 'j1',
    sender_role: 'joki',
    message: 'Halo kak, sudah selesai bab 1-3, tinggal bab 4-5 ya. Estimasi besok sore sudah selesai.',
    is_read: true,
    created_at: '2026-02-18T10:35:00Z',
  },
  {
    id: '3',
    order_id: 'DF-ABC123',
    sender_id: '1',
    sender_role: 'customer',
    message: 'Oke terima kasih, jangan lupa referensi jurnal minimal 10 ya.',
    is_read: false,
    created_at: '2026-02-18T10:40:00Z',
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: '1',
    user_id: '1',
    title: 'Order Diproses',
    message: 'Order DF-ABC123 sedang dikerjakan oleh tim kami.',
    type: 'order_update',
    is_read: false,
    created_at: '2026-02-18T12:00:00Z',
  },
  {
    id: '2',
    user_id: '1',
    title: 'Flash Sale! 🔥',
    message: 'Diskon 30% untuk semua layanan akademik. Gunakan kode FLASH30.',
    type: 'promo',
    is_read: false,
    created_at: '2026-02-18T09:00:00Z',
  },
];

export const MOCK_VOUCHERS: Voucher[] = [
  {
    id: '1',
    code: 'WELCOME20',
    discount_percent: 20,
    discount_amount: 0,
    min_order: 100000,
    max_discount: 50000,
    valid_until: '2026-03-31',
    usage_count: 145,
    max_usage: 500,
    is_active: true,
  },
  {
    id: '2',
    code: 'FLASH30',
    discount_percent: 30,
    discount_amount: 0,
    min_order: 200000,
    max_discount: 100000,
    valid_until: '2026-02-28',
    usage_count: 89,
    max_usage: 200,
    is_active: true,
  },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: 'Rina Maharani',
    university: 'Universitas Indonesia',
    text: 'Makalah saya selesai tepat waktu dan kualitasnya sangat bagus. Dosen saya kasih nilai A!',
    rating: 5,
    avatar: null,
  },
  {
    id: 2,
    name: 'Fajar Hidayat',
    university: 'ITB',
    text: 'Website e-commerce yang dibuat sangat profesional. Bahkan lebih bagus dari ekspektasi saya.',
    rating: 5,
    avatar: null,
  },
  {
    id: 3,
    name: 'Siti Nurhaliza',
    university: 'UGM',
    text: 'Konsultasi skripsinya sangat membantu! Advisor saya langsung approve bab 1-3.',
    rating: 5,
    avatar: null,
  },
  {
    id: 4,
    name: 'Dimas Prasetyo',
    university: 'Unair',
    text: 'Tugas pemrograman Python saya dikerjakan dengan sangat rapi dan ada penjelasan kode-nya juga.',
    rating: 5,
    avatar: null,
  },
  {
    id: 5,
    name: 'Anisa Dewi',
    university: 'Undip',
    text: 'PPT presentasi saya paling keren di kelas. Teman-teman pada nanya dibuat dimana 😂',
    rating: 5,
    avatar: null,
  },
  {
    id: 6,
    name: 'Raka Aditya',
    university: 'ITS',
    text: 'Desain 3D arsitektur yang dibuat sangat detail dan realistic. Worth every penny!',
    rating: 4,
    avatar: null,
  },
];
